
networks:
  dev-bridge:
    driver: bridge
    name: dev-bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
services:
  client:
    container_name: server
    image: web-server
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      dev-bridge:
        ipv4_address: 172.21.0.2
    volumes:
      - ${FRONTEND_PATH}:/var/www/html/

    ports:
      - 80:80


